### ISSUE TITLE
Criação de tema para Eventos e Festivais (segmento da Música)

### ISSUE THREAD

**Issue by uira** [redelivre/EditalDeRedes#3]
## Demanda
Um tema específico para o segmento da música, desenvolvido com base na plataforma Toque No Brasil (​http://tnb.art.br​) e igualmente integrado ao Mapas Culturais.

## Implementação
- [x] **(Pré-requisito)** Implementação das demandas #6 , #7 e #8 
- [x] Criação do Plugin @redelivre/MapasBuilder
- [x] Criação de Módulos Divi específicos
- [ ] Pesquisar e testar Divi Layouts existentes
  - https://elegantmarketplace.com/downloads/solataire/
  - https://elegantmarketplace.com/downloads/dj-1-page/
- [ ] Criação de Divi Layout Pack

## Prazo
45 Dias

**Comment by iwasthesword** [comment]
# Pesquisa
## Propostas
- Temas testados não apresentam nenhum diferencial de funcionalidade relevante. Criar um tema-filho do Divi bem customizavel sera mais pratico.

- Layout Packs têm que necessariamente serem carregados pelo front-end pós instalação, mas podemos facilitar o acesso e criar um tutorial interno

- Funcionalidades do tema: Agenda (modulo), Oportunidades (modulo), embed de players, instalação/configuração do Mapas Culturais passo-a-passo e layout pack: home, sobre, contato, agenda, galeria

## Resources

- Layout Packs para boilerplate das paginas https://www.elegantthemes.com/layouts/
- Nova API dev https://www.elegantthemes.com/blog/theme-releases/divi-3-1-has-arrived-introducing-the-new-divi-developer-api
- Novo editor que será introduzido na versão 5.0 do WP, possivel extra para os modulos https://wordpress.org/gutenberg/

**Comment by uira** [comment]
A proposta é que esse aqui seja o Tema de Eventos, focado em Festivais de Música, que são os cases que já temos...

**Comment by uira** [comment]
# HotSite - WordPress + Divi
![image](https://user-images.githubusercontent.com/89998/61014595-9f841e80-a35e-11e9-959e-f38416526ec8.png)
![image](https://user-images.githubusercontent.com/89998/61015037-91370200-a360-11e9-95b8-880ea9a0bf06.png)
![image](https://user-images.githubusercontent.com/89998/61015040-97c57980-a360-11e9-91d6-1d5ece9b9da6.png)
![image](https://user-images.githubusercontent.com/89998/61015046-9dbb5a80-a360-11e9-813e-459c5fb259c3.png)

# Programação - Tema Integrado ao Mapas Culturais
![image](https://user-images.githubusercontent.com/89998/61014620-c5112800-a35e-11e9-981b-eead9c5d942e.png)
![image](https://user-images.githubusercontent.com/89998/61014634-d22e1700-a35e-11e9-8833-9179bc89531c.png)
![image](https://user-images.githubusercontent.com/89998/61014644-e245f680-a35e-11e9-95a6-cee905919edb.png)
![image](https://user-images.githubusercontent.com/89998/61014675-0275b580-a35f-11e9-8b68-ad9d741db7cf.png)

# Projeto no Mapas
![image](https://user-images.githubusercontent.com/89998/61014824-ac554200-a35f-11e9-8383-cba03a8657f6.png)
![image](https://user-images.githubusercontent.com/89998/61014811-934c9100-a35f-11e9-8b3c-1030ab62cec4.png)
